// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOFVJ3n3fPVckF6QgsyuMcP50Y1Bhsvc',
    appId: '1:518496449348:web:d1d3782a11e1d819c75d11',
    messagingSenderId: '518496449348',
    projectId: 'newscloud-ca30d',
    authDomain: 'newscloud-ca30d.firebaseapp.com',
    storageBucket: 'newscloud-ca30d.firebasestorage.app',
    measurementId: 'G-B0R4MBWW75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3rsJlnPJP4ZijsXlVEBVE-4-qu6Sq1E',
    appId: '1:518496449348:android:2ed8240191f0966fc75d11',
    messagingSenderId: '518496449348',
    projectId: 'newscloud-ca30d',
    storageBucket: 'newscloud-ca30d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDojg9XTJGU4qiboSgZoKDN7Kd8BQpNKyQ',
    appId: '1:518496449348:ios:ee007d2839dd2a10c75d11',
    messagingSenderId: '518496449348',
    projectId: 'newscloud-ca30d',
    storageBucket: 'newscloud-ca30d.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
